services:
  adminer:
    image: adminer:standalone@sha256:370c04eb26f585c408986d89d1d9c5e62f387d4afdd5a49aa13f7c5f53790262
    ports:
      - published: $ADMINER_PORT
        target: 8080
    networks:
      - dev
    environment:
      ADMINER_DESIGN: $ADMINER_DESIGN

  local-db:
    image: postgres:13
    environment:
      POSTGRES_USER: $DEV_DB_USERNAME
      POSTGRES_PASSWORD: $DEV_DB_PASSWORD
      POSTGRES_DB: $DEV_DB_DATABASE
    ports:
      - published: $DEV_DB_PORT
        target: 5432
    networks:
      - dev
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:

networks:
  dev:
