services:
  adminer:
    image: adminer:standalone@sha256:370c04eb26f585c408986d89d1d9c5e62f387d4afdd5a49aa13f7c5f53790262
    ports:
      - published: $ADMINER_PORT
        target: 8080
    networks:
      - dev
    environment:
      ADMINER_DESIGN: $ADMINER_DESIGN

  local-db:
    image: mysql:8.0@sha256:5d1d733f32c28d47061e9d5c2b1fb49b4628c4432901632a70019ec950eda491
    environment:
      MYSQL_ROOT_PASSWORD: $DEV_DB_PASSWORD
      MYSQL_DATABASE: $DEV_DB_DATABASE
    ports:
      - published: $DEV_DB_PORT
        target: 3306
    networks:
      - dev
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:

networks:
  dev:
